resolver: lts-10.4

packages:
- examples/echoclient/
- '.'

extra-deps:
- ranges-0.2.4
- stringprep-1.0.0
- text-1.2.2.1
- xml-picklers-0.3.6
- conduit-1.3.0
- conduit-extra-1.3.0
- xml-conduit-1.8.0
- resourcet-1.2.0

flags: {}

extra-package-dbs: []
